### ISSUE TITLE
Can't get latest video using blink.save_video in HA

### ISSUE THREAD

**Issue by imperialjoy** [fronzbot/blinkpy#106]
Calling the service 'blink.save_video' does not result in a video being saved.

Here is the automation:

- alias: office camera video
  trigger:
    - platform: state
      entity_id: binary_sensor.blink_office_motion_detected
      from: 'off'
      to: 'on'
  action:
    - service: blink.save_video
      data:
        name: camera.blink_office
        filename: '/Users/joe/.homeassistant/snapshots/office-blink.mp4'     

The automation triggers, but doesn't result in an mp4 video file in that directory.  The directory is whitelisted and used for images from other cameras already.

The logbook states:
1:39 AM
office camera video has been triggered

But no video file appears, and no blink errors show up in the log file.

Is this working for anyone else?

**Describe the bug**

**To Reproduce**

1. 
2. 
3. 

**Expected behavior**

**Home Assistant version (if applicable):** <HA Version Number>

**`blinkpy` version (not needed if filling out Home Assistant version):**

**Log Output/Additional Information**
If using home-assistant, please paste the output of the log showing your error below.  If not, please include any additional useful information.

```
PASTE LOG OUTPUT HERE
```

**Comment by fronzbot** [comment]
Thanks for opening this issue.  The service is working on my end, so I have some questions that will help to narrow down this issue.

1. What home assistant version are you using?
2. What operating system are you on? (I only ask because your directory structure looks weird to me)
3. Can you confirm your `yaml` is formatted correctly (taking care to ensure the spaces are correct):
```yaml
alias: office camera video
trigger:
  - platform: state
    entity_id: binary_sensor.blink_office_motion_detected
    from: 'off'
    to: 'on'
action:
  - service: blink.save_video
    data:
      name: camera.blink_office
      filename: '/Users/joe/.homeassistant/snapshots/office-blink.mp4'
```
4. In the `states` section of the developers tool in the front end (the tab looks like `< >`), find your camera.  There should be a bunch of attributes in the third column.  Find the one that says `video`.  What does it say?
