### ISSUE TITLE
Blink HomeAssistant integration - binary_sensor.camera_motion_detection does not trigger on motion events

### ISSUE THREAD

**Issue by TazUk** [fronzbot/blinkpy#199]
**Describe the bug**
A camera's motion detection binary_sensor entity does not react to motion events in HomeAssistant v0.99.3. 
Motion events timestamps are correctly indicated in the states.camera.blink_cameraname.attributes.last_record attribute of the camera entity and match the Blink app's records.

**To Reproduce**

1. Trigger motion detection on an integrated camera.
2. Binary sensor does not change state

**Expected behavior**
Binary sensor should change state to 'on' after the component's refresh to indicate motion was detected.

HA 0.99.3 
Running in Ubuntu 18.04 under Python 3.6.4 venv

**Log Output/Additional Information**
No error is logged in HomeAssistant.

**Comment by TazUk** [comment]
I should note that I have 2 cameras on hub 1, 1 camera on hub 2.
The binary sensors associated with each camera have all shown the same behaviour over the last few days. 
I have also seen the binary_sensors triggering overnight (UK BST around 3am) when the cameras were not armed, and no blink notifications or recordings were triggered.

**Comment by fronzbot** [comment]
So following your steps, my binary sensors all flip to true. To me this means that at the very least, there's nothing wrong with the API calls or the HA integration. Your last comment makes me think it's a timezone issue when contacting blink servers (so all your stuff is delayed by 3am-trigger event).

To test that, I do have a debug option available for the HA integration you could try called [offset](https://www.home-assistant.io/components/blink/#offset). I added this specifically in case a problem like this ever arose. It'll allow you to basically adjust your motion event search in time to account for improperly handled timezones. I'm hoping this is the problem...may not know exactly how to fix it but at least I'll know where to look :smile:

**Comment by TazUk** [comment]
Thanks for responding.

I've drilled down a bit more, and compared my homeassistant history from the last few days (28th Sept 00:00 onwards) with the Blink app records and have noted the following:
Hub 1 (front room, dining room indoor cameras)
Front Room: 
    Binary sensor triggered 28th 14:59, 15:13
    App recordings: 28th 14:58
Dining Room: 
    Binary sensor triggered 29th 03:27, 03:37 
    App recordings: 29th 14:59, 30th 08:25

Hub 2 (garden camera)
    Binary sensor triggered: none
    App recordings: 30th 08:26

It's worth noting that the last_record attributes on all cameras seem to be tracking times that correspond to the Blink App clips (allowing for a 1 hour BST adjustment). 
I have just finished moving my motion detected automations to track the last_record attribute from the camera entities themselves via some template sensors.

I might track the behaviour for a few days before trying the _offset_ configuration option: should I set it to 5 minutes to reflect my 600 scan_interval?

**Comment by TazUk** [comment]
Not had an opportunity to try the offset, but I can confirm that the binary sensors are simply not triggering based on the last few days behaviour (29th Sept 00:00 to 2nd Oct 11:00).

**HomeAssistant** binary sensors (see attached image) record:
- Dining Room:
   29th Sept 03:27, 03:37
   1st Oct 08:03, 08:33, 08:53
- Front Room: no triggers
- Garden: no triggers

**Blink App**:
- Dining Room:
   1st Oct 08:02, 08:26, 08:45
   30th Sept 08:25
- Garden: 
   2nd Oct 10:51, 10:52
   30th Sep 08:36
- Front Room: no recordings for time period 29th to 2nd.

Essentially the binary sensors simply don't trigger at all as far as I can see in some instances, and will trigger randomly in others, however the camera _last_record_ attribute populates with the last event datetime as expected (example in the attached screenshots).

**Configuration** 
```
blink:
  username: !secret blink_usr
  password: !secret blink_pwd     
  scan_interval: 600
  binary_sensors:
    monitored_conditions:
      - motion_detected
```
```
input_datetime:
  last_front_room_recording:
    name: 'Last Front Room Recording'
    has_date: true
    has_time: true
  last_dining_room_recording:
    name: 'Last Dining Room Recording'
    has_date: true
    has_time: true
  last_garden_recording:
    name: 'Last Garden Recording'
    has_date: true
    has_time: true
```

Sensors (to trigger automations for motion):
```
sensors:
   - platform: template
     sensors:
    garden_recording:
       friendly_name: 'Garden Recording'
       entity_id: camera.blink_garden
       value_template: '{% if (states.camera.blink_garden.attributes.last_record != None) %}on{% else %}off{% endif %}'
    front_room_recording:
       friendly_name: 'Front Room Recording'
       entity_id: camera.blink_front_room
       value_template: '{% if (states.camera.blink_front_room.attributes.last_record != None) %}on{% else %}off{% endif %}'
    dining_room_recording:                  
       friendly_name: 'Dining Room Recording'      
       entity_id: camera.blink_dining_room
       value_template: '{% if (states.camera.blink_dining_room.attributes.last_record != None) %}on{% else %}off{% endif %}'
```

Sample automation based on template sensor (was based on binary_sensor):

```
- id: camera_blink_motiondetected_garden
  alias: 'Blink camera motion detected - Garden'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.garden_recording 
      from: 'off'
      to: 'on'
  action:
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.last_garden_recording
        time: '{{ as_timestamp(states.camera.blink_garden.attributes.last_record) | timestamp_custom("%H:%M:%S", true) }}'
        date: '{{ as_timestamp(states.camera.blink_garden.attributes.last_record) | timestamp_custom("%Y-%m-%d", true) }}'

```

![Summary](https://user-images.githubusercontent.com/1246826/66038370-da36c680-e509-11e9-9893-333ce5e67628.jpg)

Hope this makes some sort of sense.

At this point I'm doubting whether it could be a timezone issue, in as much as I would expect the binary_sensors to be firing at some point to reflect the capture motion events (but just at a different time). Given that two of three of my sensors seem to be completely dead, and the third may or may not track actual events, is there still a benefit in me testing with the _offset_ parameter?
If so, I'll write some parallel automations at the weekend and run them side by side with my last_record hack.

**Comment by fronzbot** [comment]
First off: wow.  This is an excellent debug effort! 👏 

I'm actually stumped.  Your latest info, to me, points to the `motion_detected` variable in `blinkpy` not being set for some reason (which means the binary sensor could never flip to `on`).  But those september timestamps are puzzling.  The following is stream-of-thought, so bear with me.

The way I store the motion timestamps takes the actual timestamp provided by blink [see here](https://github.com/fronzbot/blinkpy/blob/dev/blinkpy/sync_module.py#L189).  However, when we check for motion events on the server, I use a custom formatted timestamp (I used to NOT do this, which was causing problems for people not on the east coast of the US) [see here](https://github.com/fronzbot/blinkpy/blob/dev/blinkpy/helpers/util.py#L14).

Now, looking through the code there's also another thing it could be.  I only look at the first page of results [see here](https://github.com/fronzbot/blinkpy/blob/dev/blinkpy/sync_module.py#L172).  The number of items per page is limited to 25 but deleting videos in your app does not necessarily delete videos on the server, it just _marks_ them for deletion.  So if you have a lot of events, maybe the new events are being stored on a different page.... but this doesn't explain why the `last_record` variable is being set correctly and the `motion_detected` is not...damn.

I'll have to give this some more thought.   In the meantime, it may be worth trying the `offset` parameter to something ridiculous like `1440` to go back 24hrs just to see if something actually triggers.

**Comment by TazUk** [comment]
Yesterday I reverted to using the binary_sensor in my automations after rebooting the indoor system (I replaced batteries in the indoor cameras a week or so ago and wondered whether this behaviour might be a consequence of not rebooting the hub after doing so).

However during the night the dining room binary sensor tripped at 02:48  (automation last_triggered showed: 2019-10-06T01:48:02.265400+00:00) despite the associated alarm_panel being disarmed and no motion recorded in the Blink app.
When I checked the dining room camera attributes this morning the last_record showed '2018-10-05T13:42:16+00:00'. **

Based on my observations the last few days I'm still not sure that the offset parameter is going to mitigate this behaviour.
For genuine triggers (recorded by the Blink app etc) everything seems fine at the moment, ie the binary sensor fires etc.

With that in mind I'm now trying to mitigate these overnight false triggers on the binary sensor, still leveraging the template sensors I based on the last_record attribute. 
My (further) revised motion detection automations now include both binary sensor and template sensor per camera, and account for the 600 second service refresh in my configuration.

```
- id: camera_blink_motiondetected_diningroom
  alias: 'Blink camera motion detected - Dining Room'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.blink_dining_room_motion_detected
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.dining_room_recording 
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: '{{ (as_timestamp(utcnow()) - as_timestamp(states.camera.blink_dining_room.attributes.last_record) ) <= 600 }}'
      - condition: state
        entity_id: alarm_control_panel.blink_sync
        state: armed_away
  action:
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.last_dining_room_recording
        time: >
          {% if (states.camera.blink_dining_room.attributes.last_record is defined and states.camera.blink_dining_room.attributes.last_record != None) %} 
                {{ as_timestamp(states.camera.blink_dining_room.attributes.last_record) | timestamp_custom("%H:%M:%S", true) }}
          {% else %}
                {{ as_timestamp(now()) | timestamp_custom("%H:%M:%S", true) }}
          {% endif %}
        date: >
          {% if (states.camera.blink_dining_room.attributes.last_record is defined and states.camera.blink_dining_room.attributes.last_record != None) %} 
                {{ as_timestamp(states.camera.blink_dining_room.attributes.last_record) | timestamp_custom("%Y-%m-%d", true) }}
          {% else %}
                {{ as_timestamp(now()) | timestamp_custom("%Y-%m-%d", true) }}
          {% endif %}
```

I probably need to check my understanding of the expected integration behaviour at this point just to make sure I'm not rattling down a dead-end:_
- Motion detected binary sensor fires when camera system is armed and motion is detected by a camera.
- On next blink service update the camera's last_record attribute is refreshed with the timestamp of the last video.

One thing I'm not sure on is how long the 'last_record' attribute's value should persist for in-between recordings (ignoring edge cases like homeassistant restarts, etc.)

** The other thing of interest is the very old last_record attribute on the dining room camera this morning - just over 1 year ago.. This may be of interest because in the Blink App I have the storage set to "auto-delete clips older than 1 year". I suspect that the timestamp noted this morning ('2018-10-05T13:42:16+00:00') actually represents the most recent of the _purged_ clips from Blink as it would be just over 1 year ago.
Is it possible therefore that the binary_sensor is being tripped by the sensor purging occurring automatically at the Blink server end?
